[package]
name = "swc-ts-stack-checker"
version = "0.1.0"
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_atoms = "0.2"
swc_common = "0.9"
swc_ecmascript = "0.2"